[package]
name = "ve-bus-adapter"
version = "0.1.0"
authors = ["David Kern <david@mju.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
influent = "0.4"
serialport = "3.3.0"
